name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP on macOS
        if: runner.os == 'macOS'
        run: |
          curl -L https://dl.static-php.dev/static-php-cli/common/php-8.3.11-cli-macos-aarch64.tar.gz -o php.tar.gz
          tar -xzf php.tar.gz
          sudo mv php /usr/local/bin/php
          php --version

      - name: Setup PHP on Windows
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri https://dl.static-php.dev/static-php-cli/common/php-8.3.11-cli-windows-x64.zip -OutFile php.zip
          Expand-Archive -Path php.zip -DestinationPath .
          Move-Item -Path php -Destination C:\php
          C:\php\php --version

      - name: Run app
        run: php sqlite_viewer.php test/database.sqlite --port 9000 > server.log 2>&1 &
        shell: bash

      - name: Wait for server to start
        run: |
          for i in {1..10}; do
              curl -s http://localhost:9000 && break
              sleep 1
          done
        shell: bash

      - name: Run tests
        run: php test/test.php
        shell: bash

      - name: Debug
        if: always()
        run: cat server.log
        shell: bash
