name: PHP Tests

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP on macOS
        if: runner.os == 'macOS'
        uses: shivammathur/setup-php@v2

      - name: Check PHP
        run: php -v

      - name: Start server
        run: php sqlite_viewer.php test/database.sqlite --port 9000 &
        shell: bash

      - name: Run tests
        run: php test/test.php
