name: Version Compatability Tests

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  php-version-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ "7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, sqlite3
          coverage: none

      - name: Run app
        run: php sqlite_viewer.php test/database.sqlite --port 9000 > server.log 2>&1 &
        shell: bash

      - name: Wait for server to start
        run: |
          for i in {1..10}; do
              curl -s http://localhost:9000 && break
              sleep 1
          done
        shell: bash

      - name: Run tests
        run: php test/test.php
        shell: bash

      - name: Debug
        if: always()
        run: cat server.log
        shell: bash

  os-version-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-22.04', 'macos-12', 'windows-2019']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, sqlite3
          coverage: none

      - name: Run app
        run: php sqlite_viewer.php test/database.sqlite --port 9000 > server.log 2>&1 &
        shell: bash

      - name: Wait for server to start
        run: |
          for i in {1..10}; do
              curl -s http://localhost:9000 && break
              sleep 1
          done
        shell: bash

      - name: Run tests
        run: php test/test.php
        shell: bash

      - name: Debug
        if: always()
        run: cat server.log
        shell: bash
